import type {
  ActivityEntryRecord,
  IssueRecord,
  LabelRecord,
  ProjectRecord,
  StatusRecord,
  TagRecord,
  TeamRecord,
  UserRecord,
} from './records'

const demoUserIds = {
  managerMariam: 'user-mariam',
  pmNino: 'user-nino',
  pmLuka: 'user-luka',
  userAna: 'user-ana',
  userGio: 'user-gio',
  userMaya: 'user-maya',
  userDato: 'user-dato',
} as const

const demoTeamIds = {
  delivery: 'team-delivery',
  insights: 'team-insights',
} as const

const demoProjectIds = {
  atlasRollout: 'project-atlas-rollout',
  censusOps: 'project-census-ops',
  insightsHub: 'project-insights-hub',
} as const

const demoTagIds = {
  client: 'tag-client',
  questionnaire: 'tag-questionnaire',
  review: 'tag-review',
  dataUpdate: 'tag-data-update',
  internal: 'tag-internal',
  urgent: 'tag-urgent',
  followUp: 'tag-follow-up',
  research: 'tag-research',
} as const

const demoLabelIds = {
  needsUpdate: 'label-needs-update',
  readyForConfirmation: 'label-ready-for-confirmation',
  clientVisible: 'label-client-visible',
} as const

const demoIssueIds = {
  atlasFieldChecklist: 'issue-atlas-field-checklist',
  atlasClientQuestionnaire: 'issue-atlas-client-questionnaire',
  atlasKickoffSummary: 'issue-atlas-kickoff-summary',
  censusOwnershipTransfer: 'issue-census-ownership-transfer',
  censusBlockedImport: 'issue-census-blocked-import',
  insightsWeeklyDigest: 'issue-insights-weekly-digest',
  insightsTeamReview: 'issue-insights-team-review',
  atlasFinalApproval: 'issue-atlas-final-approval',
} as const

const createdAt = {
  jan06: '2026-01-06T09:00:00.000Z',
  jan08: '2026-01-08T10:15:00.000Z',
  jan10: '2026-01-10T11:00:00.000Z',
  jan12: '2026-01-12T08:45:00.000Z',
  jan14: '2026-01-14T13:20:00.000Z',
  jan16: '2026-01-16T09:30:00.000Z',
  jan18: '2026-01-18T15:10:00.000Z',
  jan20: '2026-01-20T10:00:00.000Z',
  jan21: '2026-01-21T16:40:00.000Z',
  jan22: '2026-01-22T12:00:00.000Z',
} as const

export interface DemoSeedData {
  users: UserRecord[]
  teams: TeamRecord[]
  projects: ProjectRecord[]
  statuses: StatusRecord[]
  tags: TagRecord[]
  labels: LabelRecord[]
  issues: IssueRecord[]
  activityHistory: ActivityEntryRecord[]
}

export const emptyDemoSeedData: DemoSeedData = {
  users: [],
  teams: [],
  projects: [],
  statuses: [],
  tags: [],
  labels: [],
  issues: [],
  activityHistory: [],
}

export type SeedState = {
  initialized: boolean
  data: DemoSeedData
}

export const demoUsers: UserRecord[] = [
  {
    id: demoUserIds.managerMariam,
    name: 'Mariam Kapanadze',
    email: 'mariam@demo.local',
    role: 'manager',
    teamId: null,
    avatarInitials: 'MK',
    isDemoUser: true,
  },
  {
    id: demoUserIds.pmNino,
    name: 'Nino Beridze',
    email: 'nino@demo.local',
    role: 'project-manager',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'NB',
    isDemoUser: true,
  },
  {
    id: demoUserIds.pmLuka,
    name: 'Luka Tsereteli',
    email: 'luka@demo.local',
    role: 'project-manager',
    teamId: demoTeamIds.insights,
    avatarInitials: 'LT',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userAna,
    name: 'Ana Japaridze',
    email: 'ana@demo.local',
    role: 'user',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'AJ',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userGio,
    name: 'Gio Lomidze',
    email: 'gio@demo.local',
    role: 'user',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'GL',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userMaya,
    name: 'Maya Chikovani',
    email: 'maya@demo.local',
    role: 'user',
    teamId: demoTeamIds.insights,
    avatarInitials: 'MC',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userDato,
    name: 'Dato Khatiashvili',
    email: 'dato@demo.local',
    role: 'user',
    teamId: demoTeamIds.insights,
    avatarInitials: 'DK',
    isDemoUser: true,
  },
]

export const demoTeams: TeamRecord[] = [
  {
    id: demoTeamIds.delivery,
    name: 'Delivery Operations',
    description: 'Project delivery team coordinating field work, client follow-up, and operational handoffs.',
    memberIds: [
      demoUserIds.pmNino,
      demoUserIds.userAna,
      demoUserIds.userGio,
    ],
    createdAt: createdAt.jan06,
    updatedAt: createdAt.jan20,
  },
  {
    id: demoTeamIds.insights,
    name: 'Insights and Reporting',
    description: 'Research and reporting team preparing summaries, review cycles, and stakeholder updates.',
    memberIds: [
      demoUserIds.pmLuka,
      demoUserIds.userMaya,
      demoUserIds.userDato,
    ],
    createdAt: createdAt.jan06,
    updatedAt: createdAt.jan20,
  },
]

export const demoProjects: ProjectRecord[] = [
  {
    id: demoProjectIds.atlasRollout,
    name: 'Atlas Rollout',
    description: 'Operational rollout for the next client launch wave across multiple field locations.',
    status: 'in-progress',
    ownerId: demoUserIds.pmNino,
    teamId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
    updatedAt: createdAt.jan22,
  },
  {
    id: demoProjectIds.censusOps,
    name: 'Census Ops Recovery',
    description: 'Recovery work for delayed imports, ownership gaps, and unresolved dependencies.',
    status: 'blocked',
    ownerId: demoUserIds.pmNino,
    teamId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
    updatedAt: createdAt.jan21,
  },
  {
    id: demoProjectIds.insightsHub,
    name: 'Insights Hub Refresh',
    description: 'Weekly reporting refresh with research review, digest publishing, and stakeholder checks.',
    status: 'planned',
    ownerId: demoUserIds.pmLuka,
    teamId: demoTeamIds.insights,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
    updatedAt: createdAt.jan20,
  },
]

export const demoStatuses: StatusRecord[] = [
  { id: 'new', name: 'New', isCustom: false, createdBy: null, createdAt: null },
  { id: 'planned', name: 'Planned', isCustom: false, createdBy: null, createdAt: null },
  { id: 'waiting', name: 'Waiting', isCustom: false, createdBy: null, createdAt: null },
  { id: 'blocked', name: 'Blocked', isCustom: false, createdBy: null, createdAt: null },
  { id: 'delayed', name: 'Delayed', isCustom: false, createdBy: null, createdAt: null },
  { id: 'in-progress', name: 'In Progress', isCustom: false, createdBy: null, createdAt: null },
  { id: 'done', name: 'Done', isCustom: false, createdBy: null, createdAt: null },
  { id: 'canceled', name: 'Canceled', isCustom: false, createdBy: null, createdAt: null },
]

export const demoTags: TagRecord[] = [
  {
    id: demoTagIds.client,
    name: 'Client',
    normalizedName: 'client',
    color: '#2563eb',
    usageCount: 3,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoTagIds.questionnaire,
    name: 'Questionnaire',
    normalizedName: 'questionnaire',
    color: '#9333ea',
    usageCount: 2,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoTagIds.review,
    name: 'Review',
    normalizedName: 'review',
    color: '#0f766e',
    usageCount: 2,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan10,
  },
  {
    id: demoTagIds.dataUpdate,
    name: 'Data Update',
    normalizedName: 'data update',
    color: '#0891b2',
    usageCount: 2,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
  },
  {
    id: demoTagIds.internal,
    name: 'Internal',
    normalizedName: 'internal',
    color: '#6b7280',
    usageCount: 2,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
  },
  {
    id: demoTagIds.urgent,
    name: 'Urgent',
    normalizedName: 'urgent',
    color: '#dc2626',
    usageCount: 2,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan12,
  },
  {
    id: demoTagIds.followUp,
    name: 'Follow-up',
    normalizedName: 'follow-up',
    color: '#f59e0b',
    usageCount: 2,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
  },
  {
    id: demoTagIds.research,
    name: 'Research',
    normalizedName: 'research',
    color: '#14b8a6',
    usageCount: 2,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan14,
  },
]

export const demoLabels: LabelRecord[] = [
  {
    id: demoLabelIds.needsUpdate,
    name: 'Needs Update',
    type: 'system',
    color: '#ea580c',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoLabelIds.readyForConfirmation,
    name: 'Ready for Confirmation',
    type: 'system',
    color: '#7c3aed',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoLabelIds.clientVisible,
    name: 'Client Visible',
    type: 'custom',
    color: '#1d4ed8',
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
  },
]

export const demoIssues: IssueRecord[] = [
  {
    id: demoIssueIds.atlasFieldChecklist,
    title: 'Prepare field checklist for Atlas rollout',
    description: 'Compile the final checklist for all field coordinators before the next rollout window starts.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userAna,
    curatorId: null,
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.internal, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
    updatedBy: demoUserIds.userAna,
    updatedAt: createdAt.jan20,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasClientQuestionnaire,
    title: 'Receive updated Atlas questionnaire from client representative',
    description: 'Waiting for the client-side representative to send the latest questionnaire version required for onboarding.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'waiting',
    priority: 'medium',
    ownerId: demoUserIds.pmNino,
    curatorId: null,
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.client, demoTagIds.questionnaire],
    labelIds: [demoLabelIds.needsUpdate],
    dependencyType: 'client-representative',
    dependencyTargetId: 'client-atlas-ops-lead',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan14,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasKickoffSummary,
    title: 'Coordinate Atlas kickoff summary across delivery and insights',
    description: 'Group issue to align delivery notes, research highlights, and final owner for stakeholder summary.',
    projectId: demoProjectIds.atlasRollout,
    type: 'group',
    statusId: 'blocked',
    priority: 'critical',
    ownerId: demoUserIds.userDato,
    curatorId: demoUserIds.pmLuka,
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.internal, demoTagIds.urgent, demoTagIds.review],
    labelIds: [demoLabelIds.clientVisible],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan21,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusOwnershipTransfer,
    title: 'Transfer ownership of census exception review',
    description: 'The next action moved from delivery triage to the insights reviewer after initial cleanup finished.',
    projectId: demoProjectIds.censusOps,
    type: 'individual',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userMaya,
    curatorId: null,
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.dataUpdate, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.userMaya,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan18,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusBlockedImport,
    title: 'Resolve blocked census import mapping',
    description: 'Import mapping remains blocked until the external representative confirms the final file structure.',
    projectId: demoProjectIds.censusOps,
    type: 'group',
    statusId: 'blocked',
    priority: 'critical',
    ownerId: demoUserIds.pmNino,
    curatorId: demoUserIds.pmNino,
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.urgent, demoTagIds.dataUpdate],
    labelIds: [demoLabelIds.needsUpdate],
    dependencyType: 'external-representative',
    dependencyTargetId: 'vendor-import-coordinator',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan16,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan18,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsWeeklyDigest,
    title: 'Publish weekly insights digest draft',
    description: 'Prepare the first digest draft so the PM can review it before client circulation.',
    projectId: demoProjectIds.insightsHub,
    type: 'individual',
    statusId: 'done',
    priority: 'medium',
    ownerId: demoUserIds.userGio,
    curatorId: null,
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.research, demoTagIds.review],
    labelIds: [demoLabelIds.readyForConfirmation],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmLuka,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan16,
    updatedBy: demoUserIds.userGio,
    updatedAt: createdAt.jan22,
    completedAt: createdAt.jan22,
    confirmationRequired: true,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsTeamReview,
    title: 'Review internal findings before stakeholder share-out',
    description: 'Internal group review to align interpretation, tone, and final talking points.',
    projectId: demoProjectIds.insightsHub,
    type: 'group',
    statusId: 'planned',
    priority: 'medium',
    ownerId: demoUserIds.userDato,
    curatorId: demoUserIds.pmLuka,
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.internal, demoTagIds.research],
    labelIds: [],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.insights,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan18,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan20,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasFinalApproval,
    title: 'Confirm Atlas final delivery package',
    description: 'Final package is complete and has been confirmed by the receiving project manager.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'done',
    priority: 'high',
    ownerId: demoUserIds.userAna,
    curatorId: null,
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.client, demoTagIds.review],
    labelIds: [],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmNino,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan12,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan21,
    completedAt: createdAt.jan20,
    confirmationRequired: true,
    confirmedBy: demoUserIds.pmNino,
    confirmedAt: createdAt.jan21,
  },
]

export const demoActivityHistory: ActivityEntryRecord[] = [
  {
    id: 'activity-001',
    issueId: demoIssueIds.atlasFieldChecklist,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-created',
    oldValue: null,
    newValue: 'Issue created with owner Ana Japaridze',
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-002',
    issueId: demoIssueIds.atlasClientQuestionnaire,
    actorId: demoUserIds.pmNino,
    actionType: 'status-changed',
    oldValue: 'planned',
    newValue: 'waiting',
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-003',
    issueId: demoIssueIds.atlasClientQuestionnaire,
    actorId: demoUserIds.pmNino,
    actionType: 'tag-added',
    oldValue: null,
    newValue: 'Questionnaire',
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-004',
    issueId: demoIssueIds.atlasKickoffSummary,
    actorId: demoUserIds.pmLuka,
    actionType: 'curator-changed',
    oldValue: 'Nino Beridze',
    newValue: 'Luka Tsereteli',
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-005',
    issueId: demoIssueIds.atlasKickoffSummary,
    actorId: demoUserIds.pmLuka,
    actionType: 'owner-changed',
    oldValue: 'Maya Chikovani',
    newValue: 'Dato Khatiashvili',
    createdAt: createdAt.jan20,
  },
  {
    id: 'activity-006',
    issueId: demoIssueIds.censusOwnershipTransfer,
    actorId: demoUserIds.pmLuka,
    actionType: 'owner-changed',
    oldValue: 'Ana Japaridze',
    newValue: 'Maya Chikovani',
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-007',
    issueId: demoIssueIds.censusBlockedImport,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-updated',
    oldValue: 'Waiting on vendor mapping note',
    newValue: 'Blocked until external representative confirms final file structure',
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-008',
    issueId: demoIssueIds.insightsWeeklyDigest,
    actorId: demoUserIds.userGio,
    actionType: 'issue-completed',
    oldValue: 'in-progress',
    newValue: 'done',
    createdAt: createdAt.jan22,
  },
  {
    id: 'activity-009',
    issueId: demoIssueIds.insightsWeeklyDigest,
    actorId: demoUserIds.userGio,
    actionType: 'tag-added',
    oldValue: null,
    newValue: 'Review',
    createdAt: createdAt.jan22,
  },
  {
    id: 'activity-010',
    issueId: demoIssueIds.atlasFinalApproval,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-confirmed',
    oldValue: 'Ready for Confirmation',
    newValue: 'Confirmed by Project Manager',
    createdAt: createdAt.jan21,
  },
]

export const demoSeedData: DemoSeedData = {
  users: demoUsers,
  teams: demoTeams,
  projects: demoProjects,
  statuses: demoStatuses,
  tags: demoTags,
  labels: demoLabels,
  issues: demoIssues,
  activityHistory: demoActivityHistory,
}

export const initialSeedState: SeedState = {
  initialized: false,
  data: emptyDemoSeedData,
}

export async function loadSeedData(): Promise<SeedState> {
  return {
    initialized: true,
    data: demoSeedData,
  }
}
