import type {
  ActivityEntryRecord,
  IssueRecord,
  LabelRecord,
  ProjectRecord,
  StatusRecord,
  TagRecord,
  TeamRecord,
  UserRecord,
} from './records'
import { hasPersistedDemoData, readPersistedDemoData, writeDemoData } from './demoDataLifecycle'

const demoUserIds = {
  managerMariam: 'user-mariam',
  managerIrakli: 'user-irakli',
  pmNino: 'user-nino',
  pmLuka: 'user-luka',
  pmSalome: 'user-salome',
  userAna: 'user-ana',
  userGio: 'user-gio',
  userElene: 'user-elene',
  userMaya: 'user-maya',
  userDato: 'user-dato',
  userSaba: 'user-saba',
  userTamar: 'user-tamar',
  userLevan: 'user-levan',
} as const

const demoTeamIds = {
  delivery: 'team-delivery',
  insights: 'team-insights',
  success: 'team-success',
} as const

const demoProjectIds = {
  atlasRollout: 'project-atlas-rollout',
  censusOps: 'project-census-ops',
  insightsHub: 'project-insights-hub',
  signalQaReadiness: 'project-signal-qa-readiness',
  clientResponseDesk: 'project-client-response-desk',
  onboardingPlaybook: 'project-onboarding-playbook',
} as const

const demoTagIds = {
  client: 'tag-client',
  questionnaire: 'tag-questionnaire',
  review: 'tag-review',
  dataUpdate: 'tag-data-update',
  internal: 'tag-internal',
  urgent: 'tag-urgent',
  followUp: 'tag-follow-up',
  research: 'tag-research',
  qa: 'tag-qa',
  training: 'tag-training',
  release: 'tag-release',
  stakeholder: 'tag-stakeholder',
} as const

const demoLabelIds = {
  needsUpdate: 'label-needs-update',
  readyForConfirmation: 'label-ready-for-confirmation',
  clientVisible: 'label-client-visible',
  executiveReview: 'label-executive-review',
  qaRequired: 'label-qa-required',
} as const

const demoIssueIds = {
  atlasFieldChecklist: 'issue-atlas-field-checklist',
  atlasClientQuestionnaire: 'issue-atlas-client-questionnaire',
  atlasKickoffSummary: 'issue-atlas-kickoff-summary',
  censusOwnershipTransfer: 'issue-census-ownership-transfer',
  censusBlockedImport: 'issue-census-blocked-import',
  insightsWeeklyDigest: 'issue-insights-weekly-digest',
  insightsTeamReview: 'issue-insights-team-review',
  atlasFinalApproval: 'issue-atlas-final-approval',
  atlasTrainingRoster: 'issue-atlas-training-roster',
  censusDuplicateRecords: 'issue-census-duplicate-records',
  censusLegacyExportCanceled: 'issue-census-legacy-export-canceled',
  insightsStakeholderNarrative: 'issue-insights-stakeholder-narrative',
  insightsSourceValidation: 'issue-insights-source-validation',
  qaSmokeTest: 'issue-qa-smoke-test',
  qaAccessibilityPass: 'issue-qa-accessibility-pass',
  qaReleaseChecklist: 'issue-qa-release-checklist',
  clientEscalationResponse: 'issue-client-escalation-response',
  clientResponseTemplate: 'issue-client-response-template',
  clientHealthSummary: 'issue-client-health-summary',
  onboardingOutline: 'issue-onboarding-outline',
  onboardingManagerHandoff: 'issue-onboarding-manager-handoff',
  onboardingDiscoveryCanceled: 'issue-onboarding-discovery-canceled',
} as const

const createdAt = {
  jan06: '2026-01-06T09:00:00.000Z',
  jan08: '2026-01-08T10:15:00.000Z',
  jan10: '2026-01-10T11:00:00.000Z',
  jan12: '2026-01-12T08:45:00.000Z',
  jan14: '2026-01-14T13:20:00.000Z',
  jan16: '2026-01-16T09:30:00.000Z',
  jan18: '2026-01-18T15:10:00.000Z',
  jan20: '2026-01-20T10:00:00.000Z',
  jan21: '2026-01-21T16:40:00.000Z',
  jan22: '2026-01-22T12:00:00.000Z',
  jan23: '2026-01-23T09:20:00.000Z',
  jan24: '2026-01-24T14:05:00.000Z',
  jan25: '2026-01-25T11:45:00.000Z',
  jan26: '2026-01-26T15:30:00.000Z',
  jan27: '2026-01-27T10:10:00.000Z',
  jan28: '2026-01-28T13:50:00.000Z',
  jan29: '2026-01-29T09:35:00.000Z',
  jan30: '2026-01-30T17:15:00.000Z',
} as const

export interface DemoSeedData {
  users: UserRecord[]
  teams: TeamRecord[]
  projects: ProjectRecord[]
  statuses: StatusRecord[]
  tags: TagRecord[]
  labels: LabelRecord[]
  issues: IssueRecord[]
  activityHistory: ActivityEntryRecord[]
}

export const emptyDemoSeedData: DemoSeedData = {
  users: [],
  teams: [],
  projects: [],
  statuses: [],
  tags: [],
  labels: [],
  issues: [],
  activityHistory: [],
}

export type SeedState = {
  initialized: boolean
  data: DemoSeedData
}

export const demoUsers: UserRecord[] = [
  {
    id: demoUserIds.managerMariam,
    name: 'Mariam Kapanadze',
    email: 'mariam@demo.local',
    role: 'manager',
    teamId: null,
    avatarInitials: 'MK',
    isDemoUser: true,
  },
  {
    id: demoUserIds.managerIrakli,
    name: 'Irakli Svanidze',
    email: 'irakli@demo.local',
    role: 'manager',
    teamId: null,
    avatarInitials: 'IS',
    isDemoUser: true,
  },
  {
    id: demoUserIds.pmNino,
    name: 'Nino Beridze',
    email: 'nino@demo.local',
    role: 'project-manager',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'NB',
    isDemoUser: true,
  },
  {
    id: demoUserIds.pmLuka,
    name: 'Luka Tsereteli',
    email: 'luka@demo.local',
    role: 'project-manager',
    teamId: demoTeamIds.insights,
    avatarInitials: 'LT',
    isDemoUser: true,
  },
  {
    id: demoUserIds.pmSalome,
    name: 'Salome Maisuradze',
    email: 'salome@demo.local',
    role: 'project-manager',
    teamId: demoTeamIds.success,
    avatarInitials: 'SM',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userAna,
    name: 'Ana Japaridze',
    email: 'ana@demo.local',
    role: 'user',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'AJ',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userGio,
    name: 'Gio Lomidze',
    email: 'gio@demo.local',
    role: 'user',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'GL',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userElene,
    name: 'Elene Kvirikashvili',
    email: 'elene@demo.local',
    role: 'user',
    teamId: demoTeamIds.delivery,
    avatarInitials: 'EK',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userMaya,
    name: 'Maya Chikovani',
    email: 'maya@demo.local',
    role: 'user',
    teamId: demoTeamIds.insights,
    avatarInitials: 'MC',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userDato,
    name: 'Dato Khatiashvili',
    email: 'dato@demo.local',
    role: 'user',
    teamId: demoTeamIds.insights,
    avatarInitials: 'DK',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userSaba,
    name: 'Saba Nozadze',
    email: 'saba@demo.local',
    role: 'user',
    teamId: demoTeamIds.insights,
    avatarInitials: 'SN',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userTamar,
    name: 'Tamar Abashidze',
    email: 'tamar@demo.local',
    role: 'user',
    teamId: demoTeamIds.success,
    avatarInitials: 'TA',
    isDemoUser: true,
  },
  {
    id: demoUserIds.userLevan,
    name: 'Levan Kldiashvili',
    email: 'levan@demo.local',
    role: 'user',
    teamId: demoTeamIds.success,
    avatarInitials: 'LK',
    isDemoUser: true,
  },
]

export const demoTeams: TeamRecord[] = [
  {
    id: demoTeamIds.delivery,
    name: 'Delivery Operations',
    description: 'Project delivery team coordinating field work, client follow-up, and operational handoffs.',
    memberIds: [
      demoUserIds.pmNino,
      demoUserIds.userAna,
      demoUserIds.userGio,
      demoUserIds.userElene,
    ],
    createdAt: createdAt.jan06,
    updatedAt: createdAt.jan20,
  },
  {
    id: demoTeamIds.insights,
    name: 'Insights and Reporting',
    description: 'Research and reporting team preparing summaries, review cycles, and stakeholder updates.',
    memberIds: [
      demoUserIds.pmLuka,
      demoUserIds.userMaya,
      demoUserIds.userDato,
      demoUserIds.userSaba,
    ],
    createdAt: createdAt.jan06,
    updatedAt: createdAt.jan20,
  },
  {
    id: demoTeamIds.success,
    name: 'Client Success Desk',
    description: 'Client-response and QA readiness team handling escalations, release checks, and demo-facing handoffs.',
    memberIds: [
      demoUserIds.pmSalome,
      demoUserIds.userTamar,
      demoUserIds.userLevan,
    ],
    createdAt: createdAt.jan06,
    updatedAt: createdAt.jan29,
  },
]

export const demoProjects: ProjectRecord[] = [
  {
    id: demoProjectIds.atlasRollout,
    name: 'Atlas Rollout',
    description: 'Operational rollout for the next client launch wave across multiple field locations.',
    status: 'blocked',
    ownerId: demoUserIds.pmNino,
    teamId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
    updatedAt: createdAt.jan29,
  },
  {
    id: demoProjectIds.censusOps,
    name: 'Census Ops Recovery',
    description: 'Recovery work for delayed imports, ownership gaps, and unresolved dependencies.',
    status: 'blocked',
    ownerId: demoUserIds.pmNino,
    teamId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
    updatedAt: createdAt.jan28,
  },
  {
    id: demoProjectIds.insightsHub,
    name: 'Insights Hub Refresh',
    description: 'Weekly reporting refresh with research review, digest publishing, and stakeholder checks.',
    status: 'in-progress',
    ownerId: demoUserIds.pmLuka,
    teamId: demoTeamIds.insights,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
    updatedAt: createdAt.jan29,
  },
  {
    id: demoProjectIds.signalQaReadiness,
    name: 'Signal QA Readiness',
    description: 'Completed QA and release-readiness package used to demonstrate project status sync when every issue is done.',
    status: 'done',
    ownerId: demoUserIds.pmSalome,
    teamId: demoTeamIds.success,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan18,
    updatedAt: createdAt.jan30,
  },
  {
    id: demoProjectIds.clientResponseDesk,
    name: 'Client Response Desk',
    description: 'Live client-response queue with delayed templates, waiting confirmations, and manager-visible escalations.',
    status: 'delayed',
    ownerId: demoUserIds.pmSalome,
    teamId: demoTeamIds.success,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan18,
    updatedAt: createdAt.jan30,
  },
  {
    id: demoProjectIds.onboardingPlaybook,
    name: 'Operator Onboarding Playbook',
    description: 'Internal enablement project for manager handoff, role training, and reusable operational guidance.',
    status: 'in-progress',
    ownerId: demoUserIds.pmLuka,
    teamId: demoTeamIds.insights,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan20,
    updatedAt: createdAt.jan29,
  },
]

export const demoStatuses: StatusRecord[] = [
  { id: 'new', name: 'New', isCustom: false, createdBy: null, createdAt: null },
  { id: 'planned', name: 'Planned', isCustom: false, createdBy: null, createdAt: null },
  { id: 'waiting', name: 'Waiting', isCustom: false, createdBy: null, createdAt: null },
  { id: 'blocked', name: 'Blocked', isCustom: false, createdBy: null, createdAt: null },
  { id: 'delayed', name: 'Delayed', isCustom: false, createdBy: null, createdAt: null },
  { id: 'in-progress', name: 'In Progress', isCustom: false, createdBy: null, createdAt: null },
  { id: 'done', name: 'Done', isCustom: false, createdBy: null, createdAt: null },
  { id: 'canceled', name: 'Canceled', isCustom: false, createdBy: null, createdAt: null },
]

export const demoTags: TagRecord[] = [
  {
    id: demoTagIds.client,
    name: 'Client',
    normalizedName: 'client',
    color: '#2563eb',
    usageCount: 5,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoTagIds.questionnaire,
    name: 'Questionnaire',
    normalizedName: 'questionnaire',
    color: '#9333ea',
    usageCount: 3,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoTagIds.review,
    name: 'Review',
    normalizedName: 'review',
    color: '#0f766e',
    usageCount: 5,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan10,
  },
  {
    id: demoTagIds.dataUpdate,
    name: 'Data Update',
    normalizedName: 'data update',
    color: '#0891b2',
    usageCount: 4,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
  },
  {
    id: demoTagIds.internal,
    name: 'Internal',
    normalizedName: 'internal',
    color: '#6b7280',
    usageCount: 6,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
  },
  {
    id: demoTagIds.urgent,
    name: 'Urgent',
    normalizedName: 'urgent',
    color: '#dc2626',
    usageCount: 5,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan12,
  },
  {
    id: demoTagIds.followUp,
    name: 'Follow-up',
    normalizedName: 'follow-up',
    color: '#f59e0b',
    usageCount: 5,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
  },
  {
    id: demoTagIds.research,
    name: 'Research',
    normalizedName: 'research',
    color: '#14b8a6',
    usageCount: 4,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan14,
  },
  {
    id: demoTagIds.qa,
    name: 'QA',
    normalizedName: 'qa',
    color: '#16a34a',
    usageCount: 4,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan18,
  },
  {
    id: demoTagIds.training,
    name: 'Training',
    normalizedName: 'training',
    color: '#4f46e5',
    usageCount: 3,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan20,
  },
  {
    id: demoTagIds.release,
    name: 'Release',
    normalizedName: 'release',
    color: '#059669',
    usageCount: 3,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan20,
  },
  {
    id: demoTagIds.stakeholder,
    name: 'Stakeholder',
    normalizedName: 'stakeholder',
    color: '#ca8a04',
    usageCount: 4,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan20,
  },
]

export const demoLabels: LabelRecord[] = [
  {
    id: demoLabelIds.needsUpdate,
    name: 'Needs Update',
    type: 'system',
    color: '#ea580c',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoLabelIds.readyForConfirmation,
    name: 'Ready for Confirmation',
    type: 'system',
    color: '#7c3aed',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan08,
  },
  {
    id: demoLabelIds.clientVisible,
    name: 'Client Visible',
    type: 'custom',
    color: '#1d4ed8',
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
  },
  {
    id: demoLabelIds.executiveReview,
    name: 'Executive Review',
    type: 'custom',
    color: '#be123c',
    createdBy: demoUserIds.managerMariam,
    createdAt: createdAt.jan20,
  },
  {
    id: demoLabelIds.qaRequired,
    name: 'QA Required',
    type: 'custom',
    color: '#047857',
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan20,
  },
]

export const demoIssues: IssueRecord[] = [
  {
    id: demoIssueIds.atlasFieldChecklist,
    title: 'Prepare field checklist for Atlas rollout',
    description: 'Compile the final checklist for all field coordinators before the next rollout window starts.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userAna,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.internal, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
    updatedBy: demoUserIds.userAna,
    updatedAt: createdAt.jan20,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasClientQuestionnaire,
    title: 'Receive updated Atlas questionnaire from client representative',
    description: 'Waiting for the client-side representative to send the latest questionnaire version required for onboarding.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'waiting',
    priority: 'medium',
    ownerId: demoUserIds.pmNino,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.client, demoTagIds.questionnaire],
    labelIds: [demoLabelIds.needsUpdate],
    dependencyType: 'client-representative',
    dependencyTargetId: 'client-atlas-ops-lead',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan10,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan14,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasKickoffSummary,
    title: 'Coordinate Atlas kickoff summary across delivery and insights',
    description: 'Group issue to align delivery notes, research highlights, and final owner for stakeholder summary.',
    projectId: demoProjectIds.atlasRollout,
    type: 'group',
    statusId: 'blocked',
    priority: 'critical',
    ownerId: demoUserIds.userDato,
    curatorId: demoUserIds.pmLuka,
    participantIds: [demoUserIds.userAna, demoUserIds.userDato, demoUserIds.userMaya],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.internal, demoTagIds.urgent, demoTagIds.review],
    labelIds: [demoLabelIds.clientVisible],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.delivery,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan12,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan21,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusOwnershipTransfer,
    title: 'Transfer ownership of census exception review',
    description: 'The next action moved from delivery triage to the insights reviewer after initial cleanup finished.',
    projectId: demoProjectIds.censusOps,
    type: 'individual',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userMaya,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.dataUpdate, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.userMaya,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan14,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan18,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusBlockedImport,
    title: 'Resolve blocked census import mapping',
    description: 'Import mapping remains blocked until the external representative confirms the final file structure.',
    projectId: demoProjectIds.censusOps,
    type: 'group',
    statusId: 'blocked',
    priority: 'critical',
    ownerId: demoUserIds.pmNino,
    curatorId: demoUserIds.pmNino,
    participantIds: [demoUserIds.userAna, demoUserIds.userGio],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.urgent, demoTagIds.dataUpdate],
    labelIds: [demoLabelIds.needsUpdate],
    dependencyType: 'external-representative',
    dependencyTargetId: 'vendor-import-coordinator',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan16,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan18,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsWeeklyDigest,
    title: 'Publish weekly insights digest draft',
    description: 'Prepare the first digest draft so the PM can review it before client circulation.',
    projectId: demoProjectIds.insightsHub,
    type: 'individual',
    statusId: 'done',
    priority: 'medium',
    ownerId: demoUserIds.userGio,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.research, demoTagIds.review],
    labelIds: [demoLabelIds.readyForConfirmation],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmLuka,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan16,
    updatedBy: demoUserIds.userGio,
    updatedAt: createdAt.jan22,
    completedAt: createdAt.jan22,
    confirmationRequired: true,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsTeamReview,
    title: 'Review internal findings before stakeholder share-out',
    description: 'Internal group review to align interpretation, tone, and final talking points.',
    projectId: demoProjectIds.insightsHub,
    type: 'group',
    statusId: 'planned',
    priority: 'medium',
    ownerId: demoUserIds.userDato,
    curatorId: demoUserIds.pmLuka,
    participantIds: [demoUserIds.userMaya, demoUserIds.userDato],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.internal, demoTagIds.research],
    labelIds: [],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.insights,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan18,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan20,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.atlasFinalApproval,
    title: 'Confirm Atlas final delivery package',
    description: 'Final package is complete and has been confirmed by the receiving project manager.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'done',
    priority: 'high',
    ownerId: demoUserIds.userAna,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.client, demoTagIds.review],
    labelIds: [],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmNino,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan12,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan21,
    completedAt: createdAt.jan20,
    confirmationRequired: true,
    confirmedBy: demoUserIds.pmNino,
    confirmedAt: createdAt.jan21,
  },
  {
    id: demoIssueIds.atlasTrainingRoster,
    title: 'Finalize Atlas operator training roster',
    description: 'Confirm the last training attendees and assign fallback operators before the rollout starts.',
    projectId: demoProjectIds.atlasRollout,
    type: 'individual',
    statusId: 'new',
    priority: 'medium',
    ownerId: demoUserIds.userElene,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.training, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmNino,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan23,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan23,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusDuplicateRecords,
    title: 'Review duplicate census records before import retry',
    description: 'A duplicate-record pass is waiting on a clearer vendor sample before the retry can be scheduled.',
    projectId: demoProjectIds.censusOps,
    type: 'individual',
    statusId: 'waiting',
    priority: 'medium',
    ownerId: demoUserIds.userGio,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.dataUpdate, demoTagIds.review],
    labelIds: [],
    dependencyType: 'unknown',
    dependencyTargetId: 'pending-vendor-sample',
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan20,
    updatedBy: demoUserIds.userGio,
    updatedAt: createdAt.jan24,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.censusLegacyExportCanceled,
    title: 'Cancel legacy census export cleanup',
    description: 'The old export path was canceled after the team confirmed the new import path covers the remaining cases.',
    projectId: demoProjectIds.censusOps,
    type: 'individual',
    statusId: 'canceled',
    priority: 'low',
    ownerId: demoUserIds.userAna,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.delivery,
    tagIds: [demoTagIds.dataUpdate, demoTagIds.internal],
    labelIds: [],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmNino,
    createdAt: createdAt.jan18,
    updatedBy: demoUserIds.pmNino,
    updatedAt: createdAt.jan25,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsStakeholderNarrative,
    title: 'Draft stakeholder narrative for insights refresh',
    description: 'Prepare the client-facing narrative that explains the latest research movement and open risks.',
    projectId: demoProjectIds.insightsHub,
    type: 'individual',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userMaya,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.research, demoTagIds.stakeholder],
    labelIds: [demoLabelIds.clientVisible, demoLabelIds.executiveReview],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmLuka,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan22,
    updatedBy: demoUserIds.userMaya,
    updatedAt: createdAt.jan28,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.insightsSourceValidation,
    title: 'Validate disputed research source before summary lock',
    description: 'One research source is blocked until the external representative confirms the attribution chain.',
    projectId: demoProjectIds.insightsHub,
    type: 'group',
    statusId: 'waiting',
    priority: 'high',
    ownerId: demoUserIds.userSaba,
    curatorId: demoUserIds.pmLuka,
    participantIds: [demoUserIds.userMaya, demoUserIds.userDato, demoUserIds.userSaba],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.research, demoTagIds.review, demoTagIds.followUp],
    labelIds: [demoLabelIds.needsUpdate],
    dependencyType: 'external-representative',
    dependencyTargetId: 'source-owner-confirmation',
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan23,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan26,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.qaSmokeTest,
    title: 'Complete Signal QA smoke test',
    description: 'Smoke test passed across the core dashboard, project, issue, and role-switching flows.',
    projectId: demoProjectIds.signalQaReadiness,
    type: 'individual',
    statusId: 'done',
    priority: 'high',
    ownerId: demoUserIds.userLevan,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.qa, demoTagIds.release],
    labelIds: [demoLabelIds.qaRequired],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan20,
    updatedBy: demoUserIds.userLevan,
    updatedAt: createdAt.jan28,
    completedAt: createdAt.jan28,
    confirmationRequired: true,
    confirmedBy: demoUserIds.pmSalome,
    confirmedAt: createdAt.jan29,
  },
  {
    id: demoIssueIds.qaAccessibilityPass,
    title: 'Confirm keyboard and label accessibility pass',
    description: 'Keyboard traversal, visible labels, and compact controls passed the demo-readiness check.',
    projectId: demoProjectIds.signalQaReadiness,
    type: 'individual',
    statusId: 'done',
    priority: 'medium',
    ownerId: demoUserIds.userTamar,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.qa, demoTagIds.review],
    labelIds: [demoLabelIds.readyForConfirmation, demoLabelIds.qaRequired],
    dependencyType: 'user',
    dependencyTargetId: demoUserIds.pmSalome,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan21,
    updatedBy: demoUserIds.userTamar,
    updatedAt: createdAt.jan29,
    completedAt: createdAt.jan29,
    confirmationRequired: true,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.qaReleaseChecklist,
    title: 'Confirm release-readiness checklist',
    description: 'The final release-readiness checklist is complete and available for the live demo handoff.',
    projectId: demoProjectIds.signalQaReadiness,
    type: 'group',
    statusId: 'done',
    priority: 'high',
    ownerId: demoUserIds.pmSalome,
    curatorId: demoUserIds.pmSalome,
    participantIds: [demoUserIds.userTamar, demoUserIds.userLevan],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.qa, demoTagIds.release, demoTagIds.stakeholder],
    labelIds: [],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.success,
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan22,
    updatedBy: demoUserIds.pmSalome,
    updatedAt: createdAt.jan30,
    completedAt: createdAt.jan30,
    confirmationRequired: true,
    confirmedBy: demoUserIds.managerMariam,
    confirmedAt: createdAt.jan30,
  },
  {
    id: demoIssueIds.clientEscalationResponse,
    title: 'Respond to client escalation on missing rollout context',
    description: 'Client success is waiting for the external account lead to confirm the missing rollout context.',
    projectId: demoProjectIds.clientResponseDesk,
    type: 'individual',
    statusId: 'waiting',
    priority: 'critical',
    ownerId: demoUserIds.userTamar,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.client, demoTagIds.urgent, demoTagIds.stakeholder],
    labelIds: [demoLabelIds.needsUpdate, demoLabelIds.clientVisible],
    dependencyType: 'client-representative',
    dependencyTargetId: 'client-success-lead',
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan24,
    updatedBy: demoUserIds.userTamar,
    updatedAt: createdAt.jan26,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.clientResponseTemplate,
    title: 'Repair delayed client response template',
    description: 'The response template is delayed because legal wording must be reconciled before reuse.',
    projectId: demoProjectIds.clientResponseDesk,
    type: 'individual',
    statusId: 'delayed',
    priority: 'high',
    ownerId: demoUserIds.userLevan,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.client, demoTagIds.followUp],
    labelIds: [],
    dependencyType: 'external-representative',
    dependencyTargetId: 'legal-review-owner',
    createdBy: demoUserIds.pmSalome,
    createdAt: createdAt.jan23,
    updatedBy: demoUserIds.pmSalome,
    updatedAt: createdAt.jan27,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.clientHealthSummary,
    title: 'Create client health summary for manager review',
    description: 'Summarize account health, open dependencies, and escalation context for manager review.',
    projectId: demoProjectIds.clientResponseDesk,
    type: 'group',
    statusId: 'new',
    priority: 'medium',
    ownerId: demoUserIds.pmSalome,
    curatorId: demoUserIds.pmSalome,
    participantIds: [demoUserIds.userTamar, demoUserIds.userLevan],
    teamId: demoTeamIds.success,
    tagIds: [demoTagIds.client, demoTagIds.stakeholder],
    labelIds: [demoLabelIds.executiveReview],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.managerMariam,
    createdAt: createdAt.jan26,
    updatedBy: demoUserIds.managerMariam,
    updatedAt: createdAt.jan26,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.onboardingOutline,
    title: 'Write operator onboarding outline',
    description: 'Draft the onboarding outline that explains roles, issue ownership, curator work, and confirmation flow.',
    projectId: demoProjectIds.onboardingPlaybook,
    type: 'individual',
    statusId: 'planned',
    priority: 'medium',
    ownerId: demoUserIds.userSaba,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.training, demoTagIds.internal],
    labelIds: [],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan22,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan24,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.onboardingManagerHandoff,
    title: 'Prepare manager handoff training issue',
    description: 'Create a compact training example that shows manager triage, PM ownership, and user execution in one flow.',
    projectId: demoProjectIds.onboardingPlaybook,
    type: 'group',
    statusId: 'in-progress',
    priority: 'high',
    ownerId: demoUserIds.userElene,
    curatorId: demoUserIds.pmLuka,
    participantIds: [demoUserIds.userElene, demoUserIds.userSaba, demoUserIds.userTamar],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.training, demoTagIds.stakeholder, demoTagIds.internal],
    labelIds: [demoLabelIds.clientVisible],
    dependencyType: 'team',
    dependencyTargetId: demoTeamIds.delivery,
    createdBy: demoUserIds.managerIrakli,
    createdAt: createdAt.jan24,
    updatedBy: demoUserIds.userElene,
    updatedAt: createdAt.jan29,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
  {
    id: demoIssueIds.onboardingDiscoveryCanceled,
    title: 'Cancel outdated discovery note import',
    description: 'The old discovery note import was canceled after the current playbook outline replaced it.',
    projectId: demoProjectIds.onboardingPlaybook,
    type: 'individual',
    statusId: 'canceled',
    priority: 'low',
    ownerId: demoUserIds.userMaya,
    curatorId: null,
    participantIds: [],
    teamId: demoTeamIds.insights,
    tagIds: [demoTagIds.research, demoTagIds.internal],
    labelIds: [],
    dependencyType: 'none',
    dependencyTargetId: null,
    createdBy: demoUserIds.pmLuka,
    createdAt: createdAt.jan20,
    updatedBy: demoUserIds.pmLuka,
    updatedAt: createdAt.jan27,
    completedAt: null,
    confirmationRequired: false,
    confirmedBy: null,
    confirmedAt: null,
  },
]

export const demoActivityHistory: ActivityEntryRecord[] = [
  {
    id: 'activity-001',
    issueId: demoIssueIds.atlasFieldChecklist,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.atlasFieldChecklist,
      label: 'Prepare field checklist for Atlas rollout',
    },
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-002',
    issueId: demoIssueIds.atlasClientQuestionnaire,
    actorId: demoUserIds.pmNino,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'planned', label: 'Planned' },
    newValue: { kind: 'status', id: 'waiting', label: 'Waiting' },
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-003',
    issueId: demoIssueIds.atlasClientQuestionnaire,
    actorId: demoUserIds.pmNino,
    actionType: 'tag-added',
    oldValue: null,
    newValue: { kind: 'tag', id: demoTagIds.questionnaire, label: 'Questionnaire' },
    createdAt: createdAt.jan14,
  },
  {
    id: 'activity-004',
    issueId: demoIssueIds.atlasKickoffSummary,
    actorId: demoUserIds.pmLuka,
    actionType: 'curator-changed',
    oldValue: { kind: 'user', id: demoUserIds.pmNino, label: 'Nino Beridze' },
    newValue: { kind: 'user', id: demoUserIds.pmLuka, label: 'Luka Tsereteli' },
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-005',
    issueId: demoIssueIds.atlasKickoffSummary,
    actorId: demoUserIds.pmLuka,
    actionType: 'owner-changed',
    oldValue: { kind: 'user', id: demoUserIds.userMaya, label: 'Maya Chikovani' },
    newValue: { kind: 'user', id: demoUserIds.userDato, label: 'Dato Khatiashvili' },
    createdAt: createdAt.jan20,
  },
  {
    id: 'activity-006',
    issueId: demoIssueIds.censusOwnershipTransfer,
    actorId: demoUserIds.pmLuka,
    actionType: 'owner-changed',
    oldValue: { kind: 'user', id: demoUserIds.userAna, label: 'Ana Japaridze' },
    newValue: { kind: 'user', id: demoUserIds.userMaya, label: 'Maya Chikovani' },
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-007',
    issueId: demoIssueIds.censusBlockedImport,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-updated',
    oldValue: { kind: 'text', id: null, label: 'Waiting on vendor mapping note' },
    newValue: {
      kind: 'text',
      id: null,
      label: 'Blocked until external representative confirms final file structure',
    },
    createdAt: createdAt.jan18,
  },
  {
    id: 'activity-008',
    issueId: demoIssueIds.insightsWeeklyDigest,
    actorId: demoUserIds.userGio,
    actionType: 'issue-completed',
    oldValue: { kind: 'status', id: 'in-progress', label: 'In Progress' },
    newValue: { kind: 'status', id: 'done', label: 'Done' },
    createdAt: createdAt.jan22,
  },
  {
    id: 'activity-009',
    issueId: demoIssueIds.insightsWeeklyDigest,
    actorId: demoUserIds.userGio,
    actionType: 'tag-added',
    oldValue: null,
    newValue: { kind: 'tag', id: demoTagIds.review, label: 'Review' },
    createdAt: createdAt.jan22,
  },
  {
    id: 'activity-010',
    issueId: demoIssueIds.atlasFinalApproval,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-confirmed',
    oldValue: {
      kind: 'label',
      id: demoLabelIds.readyForConfirmation,
      label: 'Ready for Confirmation',
    },
    newValue: { kind: 'text', id: null, label: 'Confirmed by Project Manager' },
    createdAt: createdAt.jan21,
  },
  {
    id: 'activity-011',
    issueId: demoIssueIds.atlasTrainingRoster,
    actorId: demoUserIds.pmNino,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.atlasTrainingRoster,
      label: 'Finalize Atlas operator training roster',
    },
    createdAt: createdAt.jan23,
  },
  {
    id: 'activity-012',
    issueId: demoIssueIds.censusDuplicateRecords,
    actorId: demoUserIds.userGio,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'planned', label: 'Planned' },
    newValue: { kind: 'status', id: 'waiting', label: 'Waiting' },
    createdAt: createdAt.jan24,
  },
  {
    id: 'activity-013',
    issueId: demoIssueIds.censusLegacyExportCanceled,
    actorId: demoUserIds.pmNino,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'planned', label: 'Planned' },
    newValue: { kind: 'status', id: 'canceled', label: 'Canceled' },
    createdAt: createdAt.jan25,
  },
  {
    id: 'activity-014',
    issueId: demoIssueIds.insightsStakeholderNarrative,
    actorId: demoUserIds.userMaya,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'planned', label: 'Planned' },
    newValue: { kind: 'status', id: 'in-progress', label: 'In Progress' },
    createdAt: createdAt.jan28,
  },
  {
    id: 'activity-015',
    issueId: demoIssueIds.insightsSourceValidation,
    actorId: demoUserIds.pmLuka,
    actionType: 'label-added',
    oldValue: null,
    newValue: { kind: 'label', id: demoLabelIds.needsUpdate, label: 'Needs Update' },
    createdAt: createdAt.jan26,
  },
  {
    id: 'activity-016',
    issueId: demoIssueIds.qaSmokeTest,
    actorId: demoUserIds.userLevan,
    actionType: 'issue-completed',
    oldValue: { kind: 'status', id: 'in-progress', label: 'In Progress' },
    newValue: { kind: 'status', id: 'done', label: 'Done' },
    createdAt: createdAt.jan28,
  },
  {
    id: 'activity-017',
    issueId: demoIssueIds.qaSmokeTest,
    actorId: demoUserIds.pmSalome,
    actionType: 'issue-confirmed',
    oldValue: {
      kind: 'label',
      id: demoLabelIds.readyForConfirmation,
      label: 'Ready for Confirmation',
    },
    newValue: { kind: 'text', id: null, label: 'Confirmed after smoke test pass' },
    createdAt: createdAt.jan29,
  },
  {
    id: 'activity-018',
    issueId: demoIssueIds.qaAccessibilityPass,
    actorId: demoUserIds.userTamar,
    actionType: 'confirmation-requested',
    oldValue: null,
    newValue: {
      kind: 'label',
      id: demoLabelIds.readyForConfirmation,
      label: 'Ready for Confirmation',
    },
    createdAt: createdAt.jan29,
  },
  {
    id: 'activity-019',
    issueId: demoIssueIds.qaReleaseChecklist,
    actorId: demoUserIds.managerMariam,
    actionType: 'issue-confirmed',
    oldValue: {
      kind: 'label',
      id: demoLabelIds.readyForConfirmation,
      label: 'Ready for Confirmation',
    },
    newValue: { kind: 'text', id: null, label: 'Release checklist accepted for live demo' },
    createdAt: createdAt.jan30,
  },
  {
    id: 'activity-020',
    issueId: demoIssueIds.clientEscalationResponse,
    actorId: demoUserIds.pmSalome,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.clientEscalationResponse,
      label: 'Respond to client escalation on missing rollout context',
    },
    createdAt: createdAt.jan24,
  },
  {
    id: 'activity-021',
    issueId: demoIssueIds.clientEscalationResponse,
    actorId: demoUserIds.userTamar,
    actionType: 'label-added',
    oldValue: null,
    newValue: { kind: 'label', id: demoLabelIds.needsUpdate, label: 'Needs Update' },
    createdAt: createdAt.jan26,
  },
  {
    id: 'activity-022',
    issueId: demoIssueIds.clientResponseTemplate,
    actorId: demoUserIds.pmSalome,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'waiting', label: 'Waiting' },
    newValue: { kind: 'status', id: 'delayed', label: 'Delayed' },
    createdAt: createdAt.jan27,
  },
  {
    id: 'activity-023',
    issueId: demoIssueIds.clientHealthSummary,
    actorId: demoUserIds.managerMariam,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.clientHealthSummary,
      label: 'Create client health summary for manager review',
    },
    createdAt: createdAt.jan26,
  },
  {
    id: 'activity-024',
    issueId: demoIssueIds.onboardingOutline,
    actorId: demoUserIds.pmLuka,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.onboardingOutline,
      label: 'Write operator onboarding outline',
    },
    createdAt: createdAt.jan22,
  },
  {
    id: 'activity-025',
    issueId: demoIssueIds.onboardingManagerHandoff,
    actorId: demoUserIds.managerIrakli,
    actionType: 'issue-created',
    oldValue: null,
    newValue: {
      kind: 'issue',
      id: demoIssueIds.onboardingManagerHandoff,
      label: 'Prepare manager handoff training issue',
    },
    createdAt: createdAt.jan24,
  },
  {
    id: 'activity-026',
    issueId: demoIssueIds.onboardingManagerHandoff,
    actorId: demoUserIds.userElene,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'planned', label: 'Planned' },
    newValue: { kind: 'status', id: 'in-progress', label: 'In Progress' },
    createdAt: createdAt.jan29,
  },
  {
    id: 'activity-027',
    issueId: demoIssueIds.onboardingDiscoveryCanceled,
    actorId: demoUserIds.pmLuka,
    actionType: 'status-changed',
    oldValue: { kind: 'status', id: 'new', label: 'New' },
    newValue: { kind: 'status', id: 'canceled', label: 'Canceled' },
    createdAt: createdAt.jan27,
  },
]

export const demoSeedData: DemoSeedData = {
  users: demoUsers,
  teams: demoTeams,
  projects: demoProjects,
  statuses: demoStatuses,
  tags: demoTags,
  labels: demoLabels,
  issues: demoIssues,
  activityHistory: demoActivityHistory,
}

export const initialSeedState: SeedState = {
  initialized: false,
  data: emptyDemoSeedData,
}

export async function loadSeedData(): Promise<SeedState> {
  if (await hasPersistedDemoData()) {
    return {
      initialized: true,
      data: await readPersistedDemoData(),
    }
  }

  const persistedData = await writeDemoData(demoSeedData)

  return {
    initialized: true,
    data: persistedData,
  }
}
